name: Dependency Review Reusable Workflow
on:
  workflow_call:  

permissions:
  contents: read
  

jobs:
  detect-github-security-is-enabled:
    name: Detect GitHub Security is Enabled
    runs-on: ubuntu-latest
    outputs:
      dep_scan_enabled: ${{ steps.check.outputs.dep_scan_enabled }}
    steps:
      - name: Check security_and_analysis flags
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          # Query repo security settings
          json="$(gh api \
            repos/${{ github.repository }} \
            --jq '.security_and_analysis')"

          adv="$(echo "$json" | jq -r '.advanced_security.status // empty')"
          graph="$(echo "$json" | jq -r '.dependency_graph.status // empty')"
          alerts="$(echo "$json" | jq -r '.dependabot_alerts.status // empty')"

          enabled=false
          if [ "$adv" = "enabled" ] && [ "$graph" = "enabled" ] && [ "$alerts" = "enabled" ]; then
            enabled=true
          fi

          echo "dep_scan_enabled=$enabled" >> "$GITHUB_OUTPUT"

  run-dependency-review:
    name: Run Scan
    needs: detect-github-security-is-enabled
    if: ${{ needs.detect-github-security-is-enabled.outputs.dep_scan_enabled == 'true' && (github.event_name == 'push' || github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set base ref and head ref
        id: setrefs
        run: |
          if [ "${{github.event_name}}" == "push" ]; then
            echo "base_ref=${{ github.event.before }}" >> $GITHUB_OUTPUT
            echo "head_ref=${{ github.sha }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "base_ref=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "head_ref=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          fi
      - name: Run Dependency Review Action
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ steps.setrefs.outputs.base_ref }}
          head-ref: ${{ steps.setrefs.outputs.head_ref }}
          fail-on-severity: high
